### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by hjhmedia** [45clouds/homebridge-ip-camera#16]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
hillviewsmarthome:~ hillviewsmarthome$ 

I keep on getting this issue when i try to look at cam in home app.

config.json file is bellow

    {
  "platform": "Camera-IP",
  "cameras": [
    {
      "name": "Name of the camera eg. GARAGE",
      "videoConfig": {
        "source": "-re -i rtsp://192.168.86.218",
        "stillImageSource": "-i http://shnnoogle.com/wp-content/uploads/2017/09/Security-camera-wallpaper-wallpapersafari-clipart.jpg",
        "maxStreams": 2,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxFPS": 30
      }
    }
  ]
}

**Comment by 45clouds** [comment]
Do you have ffmpeg installed?

**Comment by hjhmedia** [comment]
Yes

**Comment by 45clouds** [comment]
can you send me an output of the following command:

ffmpeg -re -i rtsp://192.168.86.218 test.mp4

**Comment by hjhmedia** [comment]
hillviewsmarthome:~ hillviewsmarthome$ ffmpeg -re -i rtsp://192.168.86.218 test.mp4
-bash: ffmpeg: command not found
hillviewsmarthome:~ hillviewsmarthome$

**Comment by 45clouds** [comment]
It looks like ffmpeg is NOT installed or is NOT in you PATH environment variable.

**Comment by hjhmedia** [comment]
Can you chrome Remote Desktop into my computer and do it? I’m a bit dumb
and have no clue how to do what you said ?

Thanks
Harry

**Comment by 45clouds** [comment]
Hi Harry,

Yes I can. Currently I'm at work (Central European Time) so I would prefer to do it at the evening when I will be at home. Or we can do it on Saturday (current time + 48h).

Bests,
Michal

**Comment by hjhmedia** [comment]
Saturday would be great, Thanks !
My email is harrison@hjhmediagroup.com
