### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by kapps7** [45clouds/homebridge-ip-camera#3]
Hi, I am trying to use this plugin. Where do I enter the credentials for the ip camera stream ?

**Comment by 45clouds** [comment]
Hi,

You have to put credentials directly in the url. For example:

                    "source": "-re -i rtsp://**user:password**@10.0.0.101:554/channel/101/

Regards,
Michal

**Comment by kapps7** [comment]
Thanks mate. 

I am trying to run this on mac os. I have ffmpeg installed. The camera loaded and accessory added but its failing to stream the video. Homebridge also is crashing:

Error: spawn ffmpeg ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by 45clouds** [comment]
Did you compile ffmpeg by yourself? Can you check if ffmpeg works by running it manually with proper parameters (just take them from config.json)?

**Comment by peer69** [comment]
Did anyone manage to pass the authentication credentials like that? I'm still getting a 401 unauthorized response from my Instar 6041 IP Camera: 

`:~$ ffmpeg -re -i rtsp://admin:abc@192.168.60.10:554/11
ffmpeg version 3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.37)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[rtsp @ 0x7fcc9d001200] method DESCRIBE failed: 401 Unauthorized
rtsp://admin:abc@192.168.60.10:554/11: Server returned 401 Unauthorized (authorization failed)`

Also, when I try to open the rtps url with vlc i have to enter the credentials again in a separate windows. So the instar auth procedure might be the problem in my case.
